HydrologicEngineeringCenter/hec-dss

- heclib/Dss7/Internal/zinit.c
- heclib/javaHeclib/source/Hec_zgridStore.c
fix some typos, prevent a crash situation
> check for null data in grids (prevents crash in JNI)

- dotnet/Hec.Dss.Native/Hec.Dss.Native.vcxproj
- heclib/javaHeclib/javaHeclib.vcxproj
- test/Dss-C/Dss-C.vcxproj
using "$(ONEAPI_ROOT)compiler\latest\windows\compiler\lib\intel64_win"
> update linker directory for Intel Fortran libraries

- heclib/Makefile
- test/C/unix_test
- test/Dss-C/Makefile
- test/Fortran/Makefile
Also modified the tests to eat the systems own downfood and use complete
archive file instead of the seperate archives.
> Modified heclib.a creation to include the object files directly.

- heclib/heclib_c/src/headers/hecdssInternal.h
- heclib/javaHeclib/src/Hec_datjul.c
Version 7-IP-4? I need this version for my monolith branch to build
> Tweak to Hec_datjul for test inconsistencies between OSes

- heclib/javaHeclib/src/Hec_zcatalog.c
stop doing this for HMS - Make pathname uppercase and change "Minute" to "MIN"
> remove hms specific code

- heclib/javaHeclib/src/Hec_zgridRetrieve.c
another leak related to grids -- this on in the JNI
> fix memory leak

- heclib/Makefile
- heclib/heclib_c/Makefile
- heclib/heclib_c/src/Internal/zcatInternalSort.c
- heclib/javaHeclib/Makefile
- test/Dss-C/Makefile
Changes to make building working under ubuntu 22.01, with gcc 11.
Related to https://github.com/HydrologicEngineeringCenter/hec-dss/issues/150
I didn't manage to make test working for now, so compilation works but not tested...
> Gfortran 11

- dotnet/DotNetTests/SqueezeTesting.cs
- dotnet/Hec.Dss/DssWriter.cs
> fix Squeeze for .net and DSS version 6

- heclib/heclib_c/src/headers/hecdssInternal.h
- heclib/javaHeclib/src/Hec_ztextStore.c
len variable was used for two conflicting purposes
> create new variable : labelCount

- .gitignore
- hecdss.cppcheck
- heclib/heclib_c/src/Dss6/ztsRetrieveIrreg6.c
An initial change to some code to prevent identified memory leaks.
> Eliminate memory leak identified by Cppcheck.

- dotnet/Hec.Dss/Hec.Dss.csproj.nuspec
- dotnet/Hec.Dss/PairedData.cs
it was returning the number of ordinates, not number of curves
> fix PairedData.CurveCount property

- dotnet/Hec.Dss/Hec.Dss.csproj.nuspec
- dotnet/Hec.Dss/TimeWindow.cs
can be used when importing un-known interval excel data
> in error condition use IR-YEAR

- nuget.ps1
- nuget/hecdss.nuspec
includes powershell script to create the NuGet package
> add nuspec for the native hecdss.dll

- heclib/hecdss/hecdss.c
- nuget/hecdss.nuspec
increment nuget package number
> fix for issue #200

- heclib/hecdss/hecdss.c
- heclib/hecdss/hecdss.h
- heclib/heclib_c/src/headers/hecdssInternal.h
move comments from hecdss.c into hecdss.h
update to version 7-IS
> fill in hecdss.h with methods and documentation

- heclib/hecdss/hecdss.c
Call ztsProcessTimes for readign data (not saving)
> fix hec_dss_tsGetSizes

- heclib/heclib_c/src/Internal/ztsIrregStoreBlock.c
- heclib/heclib_c/src/Internal/ztsRegStoreBlock.c
- heclib/heclib_c/src/Internal/zwriteExisting.c
- heclib/heclib_c/src/headers/hecdssInternal.h
- test/C/endian.c
- test/Dss-C/source/mixed_record_types.c
includes regular and irregular time-series
> (for main branch) fixes for mixing floats and doubles between time-series writes

- heclib/javaHeclib/javaHeclib.vcxproj
use Multi-threaded Debug DLL (/MDd)
Was missing the 'DLL'
> update under Debug conf (javaHeclib)

- heclib/heclib_c/src/Internal/ztsStoreIrreg7.c
- heclib/heclib_c/src/headers/hecdssInternal.h
delete blocks missing in incoming data when using replace option
> fix storing irregular data

- heclib/javaHeclib/src/C_CatalogToJava.c
- heclib/javaHeclib/src/Hec_zcatalog.c
- heclib/javaHeclib/src/Hec_zopen.c
- heclib/javaHeclib/src/jni_utility.c
Thanks @adamkorynta ,  @MikeNeilson, @perrymanmd ,  @oskarhurst and Darren for helping with ideas and code.
Final fix was  in C_CatalogToJava -- 
(*env)->SetObjectField (env, cls, fid, jstr);
should have been
(*env)->SetObjectField (env, j_dssCatalog, fid, jstr);
> capture status before releasing memory

- heclib/heclib_c/src/Internal/isTsPattern.c
- heclib/heclib_c/src/headers/hecdssInternal.h
add check to make sure length of dparts are equal
> add check to make sure length of dparts are equal

- heclib/hecdss/hecdss.h
add hec_dss_CONSTANT_MAX_PATH_SIZE
> Update hecdss.h: remove duplicate prototypes, 
